version: '3'

services:

  db:
    image: mysql
    volumes:
      - /db/mysql:/var/lib/mysql
    restart: always
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE

  adminer:
    image: adminer
    container_name: adminDb
    restart: always
    ports:
      - 8082:8080
    depends_on:
      - db

  back:
    build:
      context: "./Forum-api"
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://db:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?allowPublicKeyRetrieval=true&useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'

  front:
    build:
      context: "./Forum-client"
      dockerfile: Dockerfile
    depends_on:
      - back
    expose:
      - 4200
    ports:
      - 4200:4200
